#!/bin/sh

echo "Generating runtime env.js..."

cat <<EOF > /usr/share/nginx/html/env.js
window._env_ = {
  REACT_APP_BACKEND_URL: "${REACT_APP_BACKEND_URL}",
  REACT_APP_FRONTEND_URL: "${REACT_APP_FRONTEND_URL}",
  REACT_APP_GRAFANA_URL: "${REACT_APP_GRAFANA_URL}",
  REACT_APP_GRAFANA_URL2: "${REACT_APP_GRAFANA_URL2}",
  REACT_APP_HORIZON_REPORT_URL: "${REACT_APP_HORIZON_REPORT_URL}",
  REACT_APP_KEYCLOAK_URL: "${REACT_APP_KEYCLOAK_URL}",
  REACT_APP_INFLUXDB_DATASOURCE_LINUX: "${REACT_APP_INFLUXDB_DATASOURCE_LINUX}",
  REACT_APP_BUCKET_LINUX: "${REACT_APP_BUCKET_LINUX}",
  REACT_APP_DASHBOARD_UID_LINUX: "${REACT_APP_DASHBOARD_UID_LINUX}",
  REACT_APP_DASHBOARD_NAME_LINUX: "${REACT_APP_DASHBOARD_NAME_LINUX}",
  REACT_APP_INFLUXDB_DATASOURCE_WINDOWS: "${REACT_APP_INFLUXDB_DATASOURCE_WINDOWS}",
  REACT_APP_BUCKET_WINDOWS: "${REACT_APP_BUCKET_WINDOWS}",
  REACT_APP_DASHBOARD_UID_WINDOWS: "${REACT_APP_DASHBOARD_UID_WINDOWS}",
  REACT_APP_DASHBOARD_NAME_WINDOWS: "${REACT_APP_DASHBOARD_NAME_WINDOWS}",
  REACT_APP_AGENT_BACKEND_URL: "${REACT_APP_AGENT_BACKEND_URL}"
};
EOF

echo "Starting Nginx..."
exec "$@"