# ---- Build Stage ----
FROM node:21.5.0 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ---- Serve Stage ----
FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Copy the build from builder stage
COPY --from=builder /app/build .

# Copy the nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy and setup the custom entrypoint for runtime env
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 80

# Run custom entrypoint
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
