export const selectAvailablePools = (state) => state.pools?.availablePools || [];
export const selectIsPoolAvailable = (state) => !!(state.pools?.isPoolAvailable);
export const selectPoolsLoading = (state) => !!state.pools?.poolsLoading;
export const selectPoolSaveLoading = (state) => !!state.pools?.poolSaveLoading;
export const selectPoolDeleteLoading = (state) => !!state.pools?.poolDeleteLoading;
export const selectVmAvailable = (state) => state.pools?.vmAvailable || [];
export const selectMachinesLoading = (state) => !!state.pools?.machinesLoading;
export const selectUsers = (state) => state.pools?.users || [];
export const selectAssignedUsers = (state) => state.pools?.assignedUsers || [];
export const selectUsersLoading = (state) => !!state.pools?.usersLoading;
export const selectSelectedVm = (state) => state.pools?.selectedVm || null;
export const selectSelectedVmDetails = (state) => state.pools?.selectedVmDetails || null;
export const selectVmDetailsMap = (state) => state.pools?.vmDetailsMap || {};
export const selectDeletingMachine = (state) => state.pools?.deletingMachine || null;
export const selectDeletingUser = (state) => state.pools?.deletingUser || null;
export const selectPowerActionLoading = (state) => state.pools?.powerActionLoading || null;
export const selectLastPowerActionResult = (state) => state.pools?.lastPowerActionResult || null;
export const selectPoolCreationDetails = (state) => state.pools?.poolCreationDetails || {};
export const selectCreationNodes = (state) => state.pools?.creationNodes || [];
export const selectCreationTemplates = (state) => state.pools?.creationTemplates || [];
export const selectCreationIpPoolNames = (state) => state.pools?.creationIpPoolNames || [];
export const selectCreationVmwareDCs = (state) => state.pools?.creationVmwareDCs || [];
export const selectCreationVmwareFolders = (state) => state.pools?.creationVmwareFolders || [];
export const selectPoolCreationError = (state) => state.pools?.poolCreationError || null;
export const selectCurrentPoolDetails = (state) => state.pools?.currentPoolDetails || {};
