export const selectAvailablePools = (state) => state.pools?.availablePools || [];
export const selectIsPoolAvailable = (state) => !!(state.pools?.isPoolAvailable);
export const selectPoolsPagination = (state) =>
  state.pools?.poolsPagination || { page: 1, page_size: 10, total: 0, total_pages: 1, has_next: false, has_prev: false };
export const selectPoolsLoading = (state) => !!state.pools?.poolsLoading;
export const selectPoolSaveLoading = (state) => !!state.pools?.poolSaveLoading;
export const selectPoolDeleteLoading = (state) => !!state.pools?.poolDeleteLoading;
export const selectVmAvailable = (state) => state.pools?.vmAvailable || [];
export const selectMachinesLoading = (state) => !!state.pools?.machinesLoading;
export const selectUsers = (state) => state.pools?.users || [];
export const selectAssignedUsers = (state) => state.pools?.assignedUsers || [];
export const selectUsersLoading = (state) => !!state.pools?.usersLoading;
export const selectSelectedVm = (state) => state.pools?.selectedVm || null;
export const selectSelectedVmDetails = (state) => state.pools?.selectedVmDetails || null;
export const selectVmDetailsMap = (state) => state.pools?.vmDetailsMap || {};
export const selectDeletingMachine = (state) => state.pools?.deletingMachine || null;
export const selectDeletingUser = (state) => state.pools?.deletingUser || null;
export const selectPowerActionLoading = (state) => state.pools?.powerActionLoading || null;
export const selectLastPowerActionResult = (state) => state.pools?.lastPowerActionResult || null;
export const selectPoolCreationDetails = (state) => state.pools?.poolCreationDetails || {};
export const selectCreationNodes = (state) => state.pools?.creationNodes || [];
export const selectCreationTemplates = (state) => state.pools?.creationTemplates || [];
export const selectCreationIpPoolNames = (state) => state.pools?.creationIpPoolNames || [];
export const selectCreationVmwareDCs = (state) => state.pools?.creationVmwareDCs || [];
export const selectCreationVmwareFolders = (state) => state.pools?.creationVmwareFolders || [];
export const selectPoolCreationError = (state) => state.pools?.poolCreationError || null;
export const selectCurrentPoolDetails = (state) => state.pools?.currentPoolDetails || {};
export const selectCreationSwitches = (state) => state.pools?.creationSwitches || [];
export const selectCreationNodesLoading = (state) => !!state.pools?.creationNodesLoading;
export const selectProxmoxStorages = (state) => state.pools?.proxmoxStorages || [];
export const selectProxmoxStoragesLoading = (state) => !!state.pools?.proxmoxStoragesLoading;
export const selectNodeGpus = (state) => state.pools?.nodeGpus || {};
export const selectNodeGpusLoading = (state) => !!state.pools?.nodeGpusLoading;
export const selectPrivateLLMCreateLoading = (state) => !!state.pools?.privateLLMCreateLoading;
export const selectPrivateLLMCreateError = (state) => state.pools?.privateLLMCreateError || null;
export const selectPrivateLLMDeleteLoading = (state) => !!state.pools?.privateLLMDeleteLoading;
export const selectPrivateLLMDeleteError = (state) => state.pools?.privateLLMDeleteError || null;
export const selectPrivateLLMActionLoading = (state) => state.pools?.privateLLMActionLoading || null;
export const selectPrivateLLMActionError = (state) => state.pools?.privateLLMActionError || null;
export const selectPrivateLLMDetail = (state) => state.pools?.privateLLMDetail || null;
export const selectPrivateLLMDetailLoading = (state) => !!state.pools?.privateLLMDetailLoading;
export const selectPrivateLLMDetailError = (state) => state.pools?.privateLLMDetailError || null;
export const selectPrivateLLMList = (state) => state.pools?.privateLLMList || [];
export const selectPrivateLLMPagination = (state) => state.pools?.privateLLMPagination || { page: 1, page_size: 10, total: 0, total_pages: 1, has_next: false, has_prev: false };
export const selectPrivateLLMListLoading = (state) => !!state.pools?.privateLLMListLoading;
export const selectPrivateLLMListError = (state) => state.pools?.privateLLMListError || null;

